#!/usr/bin/env bash
# shellcheck shell=bash
# Runs for login sessions

command -v op >/dev/null &&
  eval "$(op inject -i "$HOME/.config/1p/op.env.exports.tpl")"

# Load keychain and add SSH key if not already added
eval "$(keychain --eval --quiet id_ed25519)"

# for fcitx5
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

# for Wayland/Sway desktop environment
if [[ "$(uname -s)" == "Linux" ]] && command -v sway >/dev/null; then
  export XDG_CURRENT_DESKTOP=sway
fi

# for KVM
export LIBVIRT_DEFAULT_URI="qemu:///system"

# shellcheck source=/dev/null
source "$HOME"/.bashrc
